### ISSUE TITLE
Tensor shape blows up in Batch EI

### ISSUE THREAD

**Issue by rzc331** [secondmind-labs/trieste#205]
Can I ask why does the size of the tensor would blow up in Batch EI?

I only have a 4-dimension search space containing 270 discrete points. When I use the default parameters with sample_size=1000 & num_query_points=3, it would generate a tensor with shape[19683000,3,3]

Output error message:
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[19683000,3,3] and type double on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:Mul]

Reducing the num_query_points to less than 3 would work but it's not really a batchwise way. Reducing sample_size will give the same error.

Got stuck here for quite some time, I would appreciate it if anyone could advice!

**Comment by joelberkeley** [comment]
is that the full stack trace? It would be good to know where it got to when it errored

**Comment by joelberkeley** [comment]
also, how many output dimensions do you have?

**Comment by rzc331** [comment]
> is that the full stack trace? It would be good to know where it got to when it errored

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2020.2.4\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2020.2.4\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Zhichu Ren/PycharmProjects/low_T_electrolyte/active_learning.py", line 108, in <module>
    batch_dataset = batch_result.try_get_final_datasets()[OBJECTIVE]
  File "C:\Users\Zhichu Ren\miniconda3\lib\site-packages\trieste\bayesian_optimizer.py", line 91, in try_get_final_datasets
    return self.final_result.unwrap().datasets
  File "C:\Users\Zhichu Ren\miniconda3\lib\site-packages\trieste\utils\misc.py", line 170, in unwrap
    raise self._exc
  File "C:\Users\Zhichu Ren\miniconda3\lib\site-packages\trieste\bayesian_optimizer.py", line 245, in optimize
    query_points, acquisition_state = acquisition_rule.acquire(
  File "C:\Users\Zhichu Ren\miniconda3\lib\site-packages\trieste\acquisition\rule.py", line 370, in acquire
    expanded_search_space = search_space ** self._num_query_points
  File "C:\Users\Zhichu Ren\miniconda3\lib\site-packages\trieste\space.py", line 75, in __pow__
    space *= self
  File "C:\Users\Zhichu Ren\miniconda3\lib\site-packages\trieste\space.py", line 151, in __mul__
    tile_self = tf.tile(self.points[:, None], [1, len(other.points), 1])
  File "C:\Users\Zhichu Ren\miniconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 11453, in tile
    return tile_eager_fallback(
  File "C:\Users\Zhichu Ren\miniconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 11493, in tile_eager_fallback
    _result = _execute.execute(b"Tile", 1, inputs=_inputs_flat, attrs=_attrs,
  File "C:\Users\Zhichu Ren\miniconda3\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[19683000,3,3] and type double on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu [Op:Tile]


My filename is active_learning.py for your reference

> also, how many output dimensions do you have?

Only one.

Thank you!

**Comment by joelberkeley** [comment]
the batch acquisition optimizer works by searching in an expanded space, then reshaping the result. For example in you case, if your search space is S, it will search in S ** num_query_points, which is S x S x S for you. That space has 270 ** 3 = 19683000 points in it. I'm unsure how you'd avoid this. Give me a moment to figure this out

**Comment by rzc331** [comment]
Ah, this makes sense. 

I thought 270 is a relatively small search space, but 270^num_query_points surely is a large number...

It seems that I need to find an alternative way to do that, but thanks anyway!!

**Comment by joelberkeley** [comment]
OK, I'll close this then. Let us know if there's anything else.

**Comment by vpicheny** [comment]
I don't think that we have a solution at the moment. For now trieste must create the batch space which has indeed 270**3=19M elements, which is probably too large depending on the machine and precision? The two solutions I see are:
1. avoid constructing the batch space and solve the problem with an ad hoc optimizer
2. using a greedy approach (populate the batch one point at a time), which we should provide soon with the local penalization approach.
