### ISSUE TITLE
potential bug with `AsynchronousOptimization`

### ISSUE THREAD

**Issue by hstojic** [secondmind-labs/trieste#485]
I encountered an issue when running the integration test `test_bayesian_optimizer_with_gpr_finds_minima_of_simple_quadratic` in a PR (#483 ) where I'm switching to using GPflow model builders

I'm using this as a model:
```python
gpr = build_gpr(initial_data, search_space)
model = GaussianProcessRegression(gpr)
```
and as acq rule `AsynchronousOptimization(num_query_points=3)` with 5 steps (doesn't change what amount of steps I use).

Here is the traceback:
```python
Traceback (most recent call last):
  File "/home/hrvoje.stojic/code/trieste/trieste/bayesian_optimizer.py", line 439, in optimize
    acquisition_state, query_points = points_or_stateful(acquisition_state)
  File "/home/hrvoje.stojic/code/trieste/trieste/acquisition/rule.py", line 526, in state_func
    state = state.remove_points(datasets[OBJECTIVE].query_points)
  File "/home/hrvoje.stojic/code/trieste/trieste/acquisition/rule.py", line 356, in remove_points
    _remove_point, points_to_remove, initializer=self.pending_points
  File "/home/hrvoje.stojic/.virtualenvs/trieste_develop/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/home/hrvoje.stojic/.virtualenvs/trieste_develop/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 602, in new_func
    return func(*args, **kwargs)
  File "/home/hrvoje.stojic/.virtualenvs/trieste_develop/lib/python3.7/site-packages/tensorflow/python/ops/functional_ops.py", line 240, in foldl_v2
    name=name)
  File "/home/hrvoje.stojic/.virtualenvs/trieste_develop/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/home/hrvoje.stojic/.virtualenvs/trieste_develop/lib/python3.7/site-packages/tensorflow/python/ops/functional_ops.py", line 156, in foldl
    maximum_iterations=n)
  File "/home/hrvoje.stojic/.virtualenvs/trieste_develop/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2777, in while_loop
    loop_vars = body(*loop_vars)
  File "/home/hrvoje.stojic/.virtualenvs/trieste_develop/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2768, in <lambda>
    body = lambda i, lv: (i + 1, orig_body(*lv))
  File "/home/hrvoje.stojic/.virtualenvs/trieste_develop/lib/python3.7/site-packages/tensorflow/python/ops/functional_ops.py", line 147, in compute
    a = fn(a, elem_i)
  File "/home/hrvoje.stojic/.virtualenvs/trieste_develop/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "/home/hrvoje.stojic/.virtualenvs/trieste_develop/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 924, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/home/hrvoje.stojic/.virtualenvs/trieste_develop/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3022, in __call__
    filtered_flat_args) = self._maybe_define_function(args, kwargs)
  File "/home/hrvoje.stojic/.virtualenvs/trieste_develop/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3444, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/hrvoje.stojic/.virtualenvs/trieste_develop/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3289, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/hrvoje.stojic/.virtualenvs/trieste_develop/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 999, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/hrvoje.stojic/.virtualenvs/trieste_develop/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 672, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/hrvoje.stojic/.virtualenvs/trieste_develop/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 986, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /home/hrvoje.stojic/code/trieste/trieste/acquisition/rule.py:337 _remove_point  *
        _, first_index_tensor = tf.math.top_k(tf.cast(are_points_equal, tf.int8), k=1)
    /home/hrvoje.stojic/.virtualenvs/trieste_develop/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:206 wrapper  **
        return target(*args, **kwargs)
    /home/hrvoje.stojic/.virtualenvs/trieste_develop/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py:5297 top_k
        return gen_nn_ops.top_kv2(input, k=k, sorted=sorted, name=name)
    /home/hrvoje.stojic/.virtualenvs/trieste_develop/lib/python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py:11438 top_kv2
        "TopKV2", input=input, k=k, sorted=sorted, name=name)
    /home/hrvoje.stojic/.virtualenvs/trieste_develop/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:750 _apply_op_helper
        attrs=attr_protos, op_def=op_def)
    /home/hrvoje.stojic/.virtualenvs/trieste_develop/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py:601 _create_op_internal
        compute_device)
    /home/hrvoje.stojic/.virtualenvs/trieste_develop/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:3565 _create_op_internal
        op_def=op_def)
    /home/hrvoje.stojic/.virtualenvs/trieste_develop/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:2042 __init__
        control_input_ops, op_def)
    /home/hrvoje.stojic/.virtualenvs/trieste_develop/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:1883 _create_c_op
        raise ValueError(str(e))

    ValueError: input must have last dimension >= k = 1 but is 0 for '{{node cond/TopKV2}} = TopKV2[T=DT_INT8, sorted=true](cond/Cast, cond/TopKV2/k)' with input shapes: [0], [] and with computed input tensors: input[1] = <1>.


Terminating optimization and returning the optimization history. You may be able to use the history to restart the process from a previous successful optimization step.
```

@apaleyes any thoughts here?

**Comment by hstojic** [comment]
if I fix the likelihood variance it works: `build_gpr(initial_data, search_space, likelihood_variance=1e-5)`

**Comment by apaleyes** [comment]
The fact that it fails on this line:

`tf.math.top_k(tf.cast(are_points_equal, tf.int8), k=1)`

most certainly indicates that this is async specific. Where exactly it goes wrong though is unclear. It would be helpful to track the shapes of inputs in the method that calls that line.
